import { Request, Response, NextFunction } from 'express';
import { FirestoreService } from '../services/firestoreService';
import { StorageService } from '../services/storageService';
import { GeminiService } from '../services/geminiService';
import { AuthenticatedRequest } from '../middleware/auth';
import { AppError } from '../utils/errorHandler';
import { Logger } from '../utils/logging';
import { z } from 'zod';


const uuidSchema = z.string().uuid('Invalid Document ID format');
const questionSchema = z.string().trim().min(1, 'Question cannot be empty').max(500, 'Question too long');

export async function handleAnalyzeDocument(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const authReq = req as AuthenticatedRequest;
    const userId = authReq.user!.uid;
    const { id } = req.params;
    const parsedId = uuidSchema.safeParse(id);
    if (!parsedId.success) throw new AppError(parsedId.error.errors[0].message, 400, 'INVALID_PARAM');
    const documentId = parsedId.data;

    // 1. Verify ownership and get document
    const document = await FirestoreService.getDocumentById(userId, documentId);
    if (!document) {
      throw new AppError('Document not found or unauthorized', 404, 'NOT_FOUND');
    }

    // 2. Check if already analyzed (return existing if so)
    const existingAnalysis = await FirestoreService.getAnalysisResult(documentId);
    if (existingAnalysis) {
      res.json({
        success: true,
        data: existingAnalysis,
      });
      return;
    }

    // 3. Update status to analyzing
    await FirestoreService.updateDocumentStatus(documentId, 'analyzing');

    // 4. Retrieve extracted text
    let documentText: string;
    try {
      documentText = await StorageService.getExtractedText(userId, documentId);
    } catch (err) {
      await FirestoreService.updateDocumentStatus(documentId, 'failed');
      throw new AppError('Could not retrieve extracted text for analysis', 500, 'STORAGE_ERROR');
    }

    if (!documentText || documentText.trim().length === 0) {
      await FirestoreService.updateDocumentStatus(documentId, 'failed');
      throw new AppError('Document has no extractable text for analysis', 400, 'EMPTY_TEXT');
    }

    // 5. Call Gemini
    try {
      const analysisResult = await GeminiService.analyzeDocument(documentId, userId, documentText);

      // 6. Save result and update status
      await FirestoreService.saveAnalysisResult(documentId, analysisResult);
      await FirestoreService.updateDocumentStatus(documentId, 'complete');

      res.json({
        success: true,
        data: analysisResult,
      });
    } catch (err) {
      await FirestoreService.updateDocumentStatus(documentId, 'failed');
      const errorMessage = err instanceof Error ? err.message : 'Unknown AI error';
      Logger.error(`Gemini analysis execution failed`, { error: errorMessage });
      // Pass the safe diagnostic message generated by GeminiService
      let statusCode = 500;
      let errorCode = 'AI_ERROR';
      if (errorMessage.includes('quota') || errorMessage.includes('rate limit') || errorMessage.includes('429')) {
        statusCode = 429;
        errorCode = 'QUOTA_EXCEEDED';
      } else if (errorMessage.includes('503') || errorMessage.includes('unavailable') || errorMessage.includes('high demand')) {
        statusCode = 503;
        errorCode = 'SERVICE_UNAVAILABLE';
      }
      throw new AppError(errorMessage, statusCode, errorCode);
    }
  } catch (error) {
    next(error);
  }
}

export async function handleGetAnalysis(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const authReq = req as AuthenticatedRequest;
    const userId = authReq.user!.uid;
    const { id } = req.params;
    const parsedId = uuidSchema.safeParse(id);
    if (!parsedId.success) throw new AppError(parsedId.error.errors[0].message, 400, 'INVALID_PARAM');
    const documentId = parsedId.data;

    // Verify ownership
    const document = await FirestoreService.getDocumentById(userId, documentId);
    if (!document) {
      throw new AppError('Document not found or unauthorized', 404, 'NOT_FOUND');
    }

    const existingAnalysis = await FirestoreService.getAnalysisResult(documentId);
    if (!existingAnalysis) {
      throw new AppError('Analysis not found for this document', 404, 'NOT_FOUND');
    }

    res.json({
      success: true,
      data: existingAnalysis,
    });
  } catch (error) {
    next(error);
  }
}


export async function handleAskQuestion(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const authReq = req as AuthenticatedRequest;
    const userId = authReq.user!.uid;
    const { id } = req.params;
    const parsedId = uuidSchema.safeParse(id);
    if (!parsedId.success) throw new AppError(parsedId.error.errors[0].message, 400, 'INVALID_PARAM');
    const documentId = parsedId.data;

    const parsedQuestion = questionSchema.safeParse(req.body.question);
    if (!parsedQuestion.success) throw new AppError(parsedQuestion.error.errors[0].message, 400, 'INVALID_INPUT');
    const question = parsedQuestion.data;

    const document = await FirestoreService.getDocumentById(userId, documentId);
    if (!document) {
      throw new AppError('Document not found or unauthorized', 404, 'NOT_FOUND');
    }

    let documentText: string;
    try {
      documentText = await StorageService.getExtractedText(userId, documentId);
    } catch (err) {
      throw new AppError('Could not retrieve extracted text for Q&A', 500, 'STORAGE_ERROR');
    }

    if (!documentText || documentText.trim().length === 0) {
      throw new AppError('Document has no extractable text', 400, 'EMPTY_TEXT');
    }

    try {
      const qaPair = await GeminiService.askQuestion(documentId, userId, documentText, question.trim());
      await FirestoreService.saveQAPair(documentId, qaPair);

      res.json({
        success: true,
        data: qaPair,
      });
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown AI error';
      Logger.error('Gemini Q&A execution failed', { error: errorMessage });
      let statusCode = 500;
      let errorCode = 'AI_ERROR';
      if (errorMessage.includes('quota') || errorMessage.includes('rate limit') || errorMessage.includes('429')) {
        statusCode = 429;
        errorCode = 'QUOTA_EXCEEDED';
      } else if (errorMessage.includes('503') || errorMessage.includes('unavailable') || errorMessage.includes('high demand')) {
        statusCode = 503;
        errorCode = 'SERVICE_UNAVAILABLE';
      }
      throw new AppError(errorMessage, statusCode, errorCode);
    }
  } catch (error) {
    next(error);
  }
}

export async function handleGetQAPairs(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const authReq = req as AuthenticatedRequest;
    const userId = authReq.user!.uid;
    const { id } = req.params;
    const parsedId = uuidSchema.safeParse(id);
    if (!parsedId.success) throw new AppError(parsedId.error.errors[0].message, 400, 'INVALID_PARAM');
    const documentId = parsedId.data;

    const document = await FirestoreService.getDocumentById(userId, documentId);
    if (!document) {
      throw new AppError('Document not found or unauthorized', 404, 'NOT_FOUND');
    }

    const qaPairs = await FirestoreService.getQAPairs(documentId);

    res.json({
      success: true,
      data: qaPairs,
    });
  } catch (error) {
    next(error);
  }
}

export async function handleCompareDocuments(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const authReq = req as AuthenticatedRequest;
    const userId = authReq.user!.uid;
    const parsedA = uuidSchema.safeParse(req.body.documentIdA);
    const parsedB = uuidSchema.safeParse(req.body.documentIdB);
    if (!parsedA.success || !parsedB.success) {
      throw new AppError('Invalid Document ID format for comparison', 400, 'INVALID_PARAM');
    }
    const documentIdA = parsedA.data;
    const documentIdB = parsedB.data;

    const docA = await FirestoreService.getDocumentById(userId, documentIdA);
    const docB = await FirestoreService.getDocumentById(userId, documentIdB);

    if (!docA || !docB) {
      throw new AppError('One or both documents not found or unauthorized', 404, 'NOT_FOUND');
    }

    let docAText: string, docBText: string;
    try {
      docAText = await StorageService.getExtractedText(userId, documentIdA);
      docBText = await StorageService.getExtractedText(userId, documentIdB);
    } catch (err) {
      throw new AppError('Could not retrieve extracted text for comparison', 500, 'STORAGE_ERROR');
    }

    if (!docAText || !docBText) {
      throw new AppError('One or both documents have no extractable text', 400, 'EMPTY_TEXT');
    }

    try {
      const comparisonResult = await GeminiService.compareDocuments(
        userId,
        documentIdA,
        documentIdB,
        docA.originalName,
        docB.originalName,
        docAText,
        docBText
      );

      await FirestoreService.saveComparisonResult(comparisonResult);

      res.json({
        success: true,
        data: comparisonResult,
      });
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown AI error';
      Logger.error('Gemini comparison execution failed', { error: errorMessage });
      let statusCode = 500;
      let errorCode = 'AI_ERROR';
      if (errorMessage.includes('quota') || errorMessage.includes('rate limit') || errorMessage.includes('429')) {
        statusCode = 429;
        errorCode = 'QUOTA_EXCEEDED';
      } else if (errorMessage.includes('503') || errorMessage.includes('unavailable') || errorMessage.includes('high demand')) {
        statusCode = 503;
        errorCode = 'SERVICE_UNAVAILABLE';
      }
      throw new AppError(errorMessage, statusCode, errorCode);
    }
  } catch (error) {
    next(error);
  }
}
